import{a as v,S,i as n}from"./assets/vendor-CsOP1TRZ.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();const q="51878894-a5638140813a030bb43789a30",E="https://pixabay.com/api/",m=async(s,e=1)=>{const a={key:q,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15};try{const o=await v.get(E,{params:a});return{hits:o.data.hits,totalHits:o.data.totalHits}}catch{throw new Error("Unable to fetch images")}},B=document.querySelector(".gallery"),P=new S(".gallery a",{captionsData:"alt",captionDelay:250}),p=s=>{const e=s.map(({webformatURL:a,largeImageURL:o,tags:t,likes:r,views:l,comments:w,downloads:b})=>`
    <li class="gallery-item">
      <a href="${o}">
        <img src="${a}" alt="${t}" />
      </a>
      <div class="info">
        <span>Likes: ${r}</span>
        <span>Views: ${l}</span>
        <span>Comments: ${w}</span>
        <span>Downloads: ${b}</span>
      </div>
    </li>
  `).join("");document.querySelector(".gallery").insertAdjacentHTML("beforeend",e),P.refresh()},R=()=>{B.innerHTML=""},g=()=>{document.getElementById("loader").classList.add("show")},y=()=>{document.getElementById("loader").classList.remove("show")},f=()=>{document.querySelector(".load-more").classList.add("visible")},h=()=>{document.querySelector(".load-more").classList.remove("visible")},L=document.querySelector(".form"),$=L.elements["search-text"],H=document.querySelector(".load-more");let u=1,c="",d=0,i=0;document.querySelector(".gallery");L.addEventListener("submit",async s=>{if(s.preventDefault(),c=$.value.trim(),c===""){n.warning({title:"Warning",message:"Please enter a search query.",position:"topRight"});return}u=1,i=0,h(),R(),g();try{const e=await m(c,u);if(!e||!e.hits||e.hits.length===0){n.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}if(p(e.hits),d=e.totalHits,i=e.hits.length,i>=d)return;f(),window.scrollTo({top:0,behavior:"smooth"})}catch(e){n.error({title:"Error",message:e.message,position:"topRight"})}finally{y()}});H.addEventListener("click",async()=>{if(i>=d){h(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}g(),u+=1;try{const e=(await m(c,u)).hits;p(e),i+=e.length;const a=document.querySelector(".gallery li");if(a){const{height:o}=a.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}i>=d?(h(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):f()}catch(s){n.error({title:"Error",message:s.message,position:"topRight"})}finally{y()}});
//# sourceMappingURL=index.js.map
