import{a as S,S as p,i as l}from"./assets/vendor-vSAb4z2s.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function a(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(t){if(t.ep)return;t.ep=!0;const o=a(t);fetch(t.href,o)}})();const q="51878894-a5638140813a030bb43789a30",E="https://pixabay.com/api/",y=async(s,e=1)=>{const a={key:q,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15};try{const r=await S.get(E,{params:a});return{hits:r.data.hits,totalHits:r.data.totalHits}}catch{throw new Error("Unable to fetch images")}},B=document.querySelector(".gallery");let P=new p(".gallery a");const g=s=>{const e=s.map(({webformatURL:a,largeImageURL:r,tags:t,likes:o,views:i,comments:b,downloads:v})=>`
    <li class="gallery-item">
      <a href="${r}">
        <img src="${a}" alt="${t}" />
      </a>
      <div class="info">
        <span>Likes: ${o}</span>
        <span>Views: ${i}</span>
        <span>Comments: ${b}</span>
        <span>Downloads: ${v}</span>
      </div>
    </li>
  `).join("");document.querySelector(".gallery").insertAdjacentHTML("beforeend",e),P.refresh()},R=()=>{B.innerHTML=""},f=()=>{document.getElementById("loader").classList.add("show")},u=()=>{document.getElementById("loader").classList.remove("show")},L=()=>{document.querySelector(".load-more").classList.add("visible")},m=()=>{document.querySelector(".load-more").classList.remove("visible")},w=document.querySelector(".form"),$=w.elements["search-text"],H=document.querySelector(".load-more");let c=1,h="",d=0,n=0;document.querySelector(".gallery");new p(".gallery a",{captionsData:"alt",captionDelay:250});w.addEventListener("submit",async s=>{s.preventDefault(),h=$.value.trim(),c=1,n=0,m(),R(),f();try{const e=await y(h,c);if(!e||!e.hits||e.hits.length===0){l.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),u();return}g(e.hits),d=e.totalHits,n=e.hits.length,n<d&&L(),window.scrollTo({top:0,behavior:"smooth"})}catch(e){l.error({title:"Error",message:e.message,position:"topRight"})}finally{u()}});H.addEventListener("click",async()=>{if(n>=d){m(),l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}f(),c+=1;try{const e=(await y(h,c)).hits;g(e),n+=e.length;const a=document.querySelector(".gallery li");if(a){const{height:r}=a.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}n>=d?(m(),l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):L()}catch(s){l.error({title:"Error",message:s.message,position:"topRight"})}finally{u()}});
//# sourceMappingURL=index.js.map
